<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container79rZKq4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container79rZKq4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container79rZKq4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container79rZKq4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container79rZKq4\App_KernelDevDebugContainer([
    'container.build_hash' => '79rZKq4',
    'container.build_id' => 'bb051d11',
    'container.build_time' => 1684407180,
], __DIR__.\DIRECTORY_SEPARATOR.'Container79rZKq4');
