<?php

namespace Container79rZKq4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qo8rK6BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qo8rK6B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qo8rK6B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'book' => ['privates', '.errored..service_locator.qo8rK6B.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.qo8rK6B": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'book' => 'App\\Entity\\Book',
            'doctrine' => '?',
        ]);
    }
}
