<?php

namespace Container79rZKq4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KJSb96P.App\Entity\Book' shared service.
     *
     * @return \App\Entity\Book
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.KJSb96P": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".');
    }
}
