<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8iEJGb\App_KernelXecuteDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8iEJGb/App_KernelXecuteDebugContainer.php') {
    touch(__DIR__.'/ContainerS8iEJGb.legacy');

    return;
}

if (!\class_exists(App_KernelXecuteDebugContainer::class, false)) {
    \class_alias(\ContainerS8iEJGb\App_KernelXecuteDebugContainer::class, App_KernelXecuteDebugContainer::class, false);
}

return new \ContainerS8iEJGb\App_KernelXecuteDebugContainer([
    'container.build_hash' => 'S8iEJGb',
    'container.build_id' => '69929358',
    'container.build_time' => 1684407878,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8iEJGb');
